### PR TITLE
WIP source location

### PR DESCRIPTION
**Pull request by capfei**

### CODE REVIEW

**Comment by ariel11** [comment]
@royaljust - thoughts on this PR adding "source url" info to the curation guidelines?

**Comment by ariel11** [comment]
@capfei - For the first sentence, thoughts on "When curating the source code location for a package component, consider where the source code was at the time the component was published."

**Comment by capfei** [comment]
@ariel1 Sounds much better!

**Comment by iamwillbar** [comment]
Thanks for the add @royaljust.

One of the challenges with source location (especially when going to the level of the source associated with a particular package version) is that it's difficult, and in some cases impossible, for a curator or consumer to verify the accuracy of that information. For packages that contain direct copies of the files from a repository you could compare those files to verify they are the same, for packages that contain compiled or transpiled outputs you can't do that and would need more sophisticated ways of verifying. Even package managers that provide more structured ways of communicating what version of the source code they come from don't verify that information and it could be spoofed as a result. The [event-stream](https://schneider.dev/blog/event-stream-vulnerability-explained/) vulnerability is a notable example of this, the content that was put in the published package differed from what was in the repository.

As provenance and pedigree information becomes more available (such as through SBOMs or transparency ledgers) it may be possible to provide more confidence that the package's contents were produced by a specific commit in a specific source location. In the meantime, there's still value in collecting and basic validation of the source location (because it may provide a starting point for others to do deeper validation) but we should be transparent about the limitations in our ability to verify the accuracy of that information.

**Comment by ariel11** [comment]
May want to add something about what @capfei raised here: https://github.com/clearlydefined/curated-data/issues/25

**Comment by bduranc** [comment]
I looked a bit deeper into the format of GitLab project URLs and they appear somewhat similar to GitHub's.

Example 1

project: https://gitlab.com/gitlab-org/omnibus-gitlab

revision (commit): https://gitlab.com/gitlab-org/omnibus-gitlab/-/commit/f108fd9d49c75a20b5e603899e24742e4fec6bd4 ([14.7.0+ce.0](https://gitlab.com/gitlab-org/omnibus-gitlab/-/tags/14.7.0+ce.0))

Example 2

(sub) project: https://gitlab.com/gitlab-org/frontend/playground/batch-issue-creator

It looks like there can be nested (sub) projects that can have multiple "/" encoded in the name. So, not sure how/if we already deal with that.

Perhaps someone more familiar with the technical aspects of GitLab topic can add on to what I have here. 

@capfei on your point about re-packaged code... I think it would be a good idea to add such a comment, especially given the fact that we now plan to accept more than one source location type. The chances of selecting the wrong one may increase :)

**Comment by capfei** [comment]
@bduranc Definitely! I will also add, to @iamwillbar's point, that our ability to accurately verify sources is limited and that we may not always be able to provide confirmation.

**Comment by nickvidal** [comment]
Close by #186, thanks all!

**Pull request closed without merging**
