### PR TITLE
Adition of custom header, footer and content wrapping. Fix #42.

### LINKED ISSUE #42: add header and footer to docs site
Make a modest attempt to style the docs site as follows

* Header that notionally looks similar (logo on left, ...)
* consider having main doc sections as the headings in the header (but only if that is relatively easy)
* add a link to the main site in the docs header
* footer that looks the same-ish as the full site with the same links
* bound the width of the docs site roughly the same as the main site. Super wide doc is hard to read anyway
* switch to Montserrat font and up the size a bit (see also #39)
* de-bullet the lists in the left nave area

### PR DESCRIPTION
**Pull request by angeloreale**
**What**

- Implementing header, footer in docs, given the ClearlyDefined main page. Tackled other minor adjustments. All referred on #42 

**Before**

- There was no header, no footer and the body was too wide.

**After**

-  Added header, footer and wrapped the container appropriately.

**Commit Summary**

 Added desktop header as per #42 request.
c93751b

Styled and scripted new header for mobile.
c2fd825

Added footer. Fix #42.
aa114ff 

**How to validate this PR**

- Pull the branch
- Build and run with `bundle exec jekyll serve`.
- Visit  https://localhost:4000 and validate both mobile and desktop.

Layouts and references: N/A

**Affected URLS**

-  https://localhost:4000/*

### CODE REVIEW

**Comment by fossygirl** [comment]
@storrisi would you mind reviewing this, please?

**Comment by storrisi** [comment]
@angeloreale from a code point of view looks good to me.

Just some notes:
- a horizontal scrollbar is displaying right now, is it possible to fix it?
- the active voice of the menu has a wrong horizontal alignment:
Schermata 2019-08-08 alle 19 07 51
you can compare this to what happens on the definitions site:
Schermata 2019-08-08 alle 19 08 50
- since the left bar is fixed, I suggest having a sticky header as well
- I can't see the content full screen anymore
- we should keep the same footer styling of the application:
Schermata 2019-08-08 alle 19 13 18

**Comment by angeloreale** [comment]
Hey @storrisi, thanks for the feedback!

I'll take a look at your notes this weekend.

**Comment by fossygirl** [comment]
@angeloreale This is looking good. Just wanted to check if you'd had time to review the comments? I'd love to merge at some point if we can. :-) We really appreciate the contribution!

**Comment by angeloreale** [comment]
Thanks @fossygirl  and sorry for the delay! I haven't forgotten this PR, it's just that I was having some busy days. I promise to take a look ASAP.

**Comment by fossygirl** [comment]
@angeloreale Sure, no rush! We appreciate the contribution and would love to get it merged at some point if possible.

**Comment by fossygirl** [comment]
@angeloreale Could we either get these comments reviewed or close the PR?

**Comment by angeloreale** [comment]
@fossygirl I'm with a deadline until Friday, will definitely work on this during the weekend. I apologize for the delay, changed jobs and moved to another state in the past months.

**Comment by angeloreale** [comment]
@fossygirl @storrisi I've issued some updates addressing the list provided.
@storrisi I've tackled all the bullet points except the fullscreen issue, which I couldn't reproduce.

Sorry for the delay folks.

**Comment by fossygirl** [comment]
@storrisi  @geneh  Could you review this when you get a chance?

**Comment by fossygirl** [comment]
@geneh Can we merge this?

**Comment by geneh** [comment]
I am going to merge this pull request. @angeloreale @fossygirl @storrisi If there are any problems at https://docs.clearlydefined.io, please let me know.
Thanks for contributing!

**Pull request merged**
