### PR TITLE
Upgraded clearlydefined wiki to git-wiki 2.2.0

### PR DESCRIPTION
**Pull request by Yehonal**
Thanks to new component system you will be able to keep
clearlydefined wiki updated with original git-wiki even if
you have not same git history. You can just import updated
components by paste them in your repo.

### CODE REVIEW

**Comment by Yehonal** [comment]
Note: i've kept the clearlydefined wiki theme/layout so you can merge without issues.

You can try it locally if you want.

**Comment by jeffmcaffer** [comment]
Thanks for the contributions @Yehonal. I did not set up git-wiki in the first place so have to ask some naive questions. Can you outline the changes and benefits that come with this change? What changes for users (readers or doc writers)? For the most part we are using this as a doc site, not a wiki or a blog.

Also, on the surface it seems like the change brings many elements of the wiki into this repo rather than being "somewhere else". Feels like it may make for a bigger maintenance challenge. Related, with all this content/code copied into our repo, how do we know what version of the original we have and that indeed it is the same as the original?

**Comment by fossygirl** [comment]
@kpfleming Could you take a look at this?

**Comment by Yehonal** [comment]
Hello

There are dozens of benefits with this new version that can be useful for
your purpose, i'll list it here:

1. Seo has been improved using github seo plugin. Also favicon has been
added to meta components

2. The modular architecture has been introduced to allow you reusing wiki
components without change original code. Now you are able to create your
custom layout and components mixing original ones together. You can just
import _include, _layout and assets folder to update the wiki, this won't
break your changes if you do not touch the original files and uses new
customization methods (read the docs for it). However i've done it for you
and the readers won't notice the differcence.

3. Jekyll and github plugins has been updated even improving local
development.

4. New configurations has been added to customize/tune up your installation.

5. I'm continuing to fix things and improve the wiki with new features (i'm
working at better responsive UI and a new internal search engine method
that is more friendly than github, when it will be ready will be easier to
share this change with you using new wiki structure)

6. There is new "Add page" button and a list of new added page in sidebar
that allows you to add new wiki content easier.

And of couse other minor fixes.

Il giorno Mar 18 Dic 2018, 23:20 Carol Smith <notifications@github.com> ha
scritto:

**Comment by Yehonal** [comment]
Moreover it will allow you to complete this https://github.com/clearlydefined/clearlydefined/issues/42 issue simply using hooks and new layout customization methods

**Comment by kpfleming** [comment]
Thanks for this work @Yehonal! I'll pull this down and render it locally this weekend to review the results, so stay tuned.

**Comment by Yehonal** [comment]
> Thanks for this work @Yehonal! I'll pull this down and render it locally this weekend to review the results, so stay tuned.

You're welcome!

PS I've pushed my last updates (2.1.14) also introducing a collapsible header on small screen. It improves  readability on small screens.

**Comment by Yehonal** [comment]
Update: upgraded to 2.1.16 with new search that replaces unfriendly github system (you can restore via _config.yml eventually)

**Comment by kpfleming** [comment]
If possible, please update the summary of this PR to reflect the version that will be merged, since it's not 2.0.
I've merged this into my personal repo so GitHub would render it, and it mostly looks and works properly. I noticed one broken link in the FAQ page (to the Code of Conduct), but that could be because of the repository path change. Also, the search box doesn't seem to work... autocomplete results show up when typing search terms, but then pressing Enter goes to the GitHub search page.

**Comment by Yehonal** [comment]
> If possible, please update the summary of this PR to reflect the version that will be merged, since it's not 2.0.
> I've merged this into my personal repo so GitHub would render it, and it mostly looks and works properly. I noticed one broken link in the FAQ page (to the Code of Conduct), but that could be because of the repository path change. Also, the search box doesn't seem to work... autocomplete results show up when typing search terms, but then pressing Enter goes to the GitHub search page.

summary updated

However, about the search, the enter button shouldn't work since now it's a real-time javascript search, so the results are shown directly below the input and you've to click on them.

I'll investigate about it now

**Comment by Yehonal** [comment]
Done. https://github.com/Yehonal/clearlydefined/commit/264a9cae6fe68ef85805461348a63c82e18d687e

**Comment by kpfleming** [comment]
Thanks, looks good to me, thanks for all your efforts to do this upgrade!

**Comment by Yehonal** [comment]
You're welcome! about links, it's a good practice to use relative form as you can see in this page:

https://blog.github.com/2013-01-31-relative-links-in-markup-files/

in FAQ page for example instead of:

`[Contributor Covenant Code of Conduct](CODE_OF_CONDUCT).`

You should use:

```
[Contributor Covenant Code of Conduct](CODE_OF_CONDUCT.md).
```

In fact putting the extensions of the file allows 2 things:

1. Github automatically converts the link to the correct page, event if a permalink is used
2. If you browse the wiki using the repository, you can still use that links because they point to the correct markdown file

**Comment by Yehonal** [comment]
Updated PR to v2.2.0 , i've introduced external link icon (wikipedia style). You can see a working example in following screen:

image

It's a must-have feature

please merge as soon as possible :)

**Comment by Yehonal** [comment]
Any news?

**Comment by nellshamrell** [comment]
Hello all,

Due to the age of this pull request, I'm going to go ahead and close it. @Yehonal thank you for this contribution and, should this be something you wish to pursue further, please feel free to update and re-open this or reach out to me here or on Discord.

**Pull request closed without merging**
