### PR TITLE
docs: add source location as per PR #148

### PR DESCRIPTION
**Pull request by nickvidal**
Add source location as per PR #148, now for the new documentation website.

### CODE REVIEW

**Review by qtomlinson — COMMENTED** [review]
LGTM.  @capfei @ariel11 @bduranc Please provide feedback.

**Review by qtomlinson — APPROVED** [review]

**Comment by bduranc** [comment]
> LGTM. @capfei @ariel11 @bduranc Please provide feedback.
Also looks good to me.

**Review by bduranc — APPROVED** [review]
Looks good to me.

**Review by capfei — APPROVED** [review]
LGTM too

**Pull request merged**
